sudo: true
branches:
  only:
  - master
  - dev
language: node_js
node_js:
- node
cache:
  directories:
  - "$HOME/website/build/"
before_install:
  - cd functions
  - echo $SERVICE_ACCOUNT_KEY | gpg --passphrase-fd 0 service-account.tar.gpg
  - tar xvf service-account.tar
  - cd ..
jobs:
  include:
  - stage: Unit tests
    name: Unit Tests Functions
    before_script:
    - cd functions
    - npm i
    script: npm run test:coverage
  - stage: Unit tests
    name: Unit Tests Website
    before_script:
    - cd website
    - npm i
    script: npm run test
  - stage: Build
    if: branch = dev
    name: Build Dev Website
    before_script:
    - cd website
    - npm i
    script:
    - npm run build-dev
    - cp -R build/. $HOME/website/build/
  - stage: Build
    if: branch = master
    name: Build Prod Website
    before_script:
    - cd website
    - npm i
    script:
    - npm run build-prod
    - cp -R build/. $HOME/website/build/
  - stage: Deploy
    name: Deploy
    before_script:
    - cp -R $HOME/website/build/. public/
    - npm install firebase-tools -g
    - cd functions
    - npm i
    - cd ..
    script:
    - firebase use --token $FIREBASE_TOKEN $FIREBASE_PROJECT_ID
    - firebase deploy --token $FIREBASE_TOKEN